In [1]:
import numpy as np
import time

In [2]:
# NumPy Arrays vs Python Lists - Execution time comparison

# large dataset
size = 10_000_000  # 10 million numbers

# Python Lists
python_list = list(range(size))

start = time.time()
list_squared = [x**2 for x in python_list]  # square of all nums
end = time.time()
print("Python list time:", end - start, "seconds")

# NumPy Arrays
numpy_array = np.array(python_list)
start = time.time()
array_squared = numpy_array ** 2  # vectorized operation
end = time.time()
print("NumPy array time:", end - start, "seconds")

Python list time: 1.464421033859253 seconds
NumPy array time: 0.060427188873291016 seconds


In [3]:
#memory occupied by python list and numpy array 
import sys

print(f"python list size={sys.getsizeof(python_list)*len(python_list)} bytes")
print(f"numpy array size={numpy_array.nbytes} bytes")

python list size=800000560000000 bytes
numpy array size=80000000 bytes


In [4]:
#creatinf numpy array
arr=np.array([1,2,3,4,5])
print(arr,type (arr), arr.dtype, arr.shape)

arr2=np.array([1,2,3,4,5,"ankit"])
print(arr2,type(arr2), arr2.dtype, arr2.shape)

arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D, arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' '5' 'ankit'] <class 'numpy.ndarray'> <U21 (6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [5]:
#built-in methods
arr1=np.zeros((2,3),dtype="int64") #prefill
print(arr1, arr1.shape)

arr2=np.ones((2,3)) #prefill
print(arr2, arr2.shape)

arr3=np.full((4,3),100) #prefill with value
print(arr3, arr3.shape)

arr4=np.eye(3)  #identity matrix
print(arr4, arr4.shape)

arr5=np.arange(0,11,2) #range element
print(arr5, arr5.shape)

arr6=np.linspace(1,100,4) #Evenly Spaced arrays
print(arr6, arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1. 1. 1.]
 [1. 1. 1.]] (2, 3)
[[100 100 100]
 [100 100 100]
 [100 100 100]
 [100 100 100]] (4, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 0  2  4  6  8 10] (6,)
[  1.  34.  67. 100.] (4,)


In [6]:
#properties
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.size)   #total no. of elements
print(arr.shape)  #dimension m*n=3x3
print(arr.dtype)  #Data type object -int64
print(arr.ndim)   #Number of dimensions -2 
print(arr.itemsize)  #Size of each element in bytes -8 for int64

9
(3, 3)
int64
2
8


In [7]:
# Creating new array with a specific type from existing array
float_arr=arr.astype(np.float64)
print(float_arr, float_arr.dtype)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [8]:
#operations on array
#01. reshaping

arr=np.array([[1,2,3],[4,5,6]])
print(arr, arr.shape)

reshaped=arr.reshape((3,2))
print(reshaped, reshaped.shape)

flattered=arr.flatten()  # convert 2D => 1D
print(flattered, flattered.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [9]:
#02. Indexing
arr=np.array([1,2,3,4,5])  
print(arr[2])         #for 1D array
print(arr[4])

arr2=np.array([[1,2,3],[4,5,6]])
print(arr2[1][2])     #for 2D array
print(arr2[0][2])

3
5
6
3


In [10]:
#03. fancy and boolean indexing
arr=np.array([1,2,3,4,5])
idx= [0,1,3]              #fancy
print(arr[idx])

print(arr[arr>2])          #boolean
print(arr[arr%2==0])
print(arr[arr%2!=0])


[1 2 4]
[3 4 5]
[2 4]
[1 3 5]


In [11]:
#04. Slicing
arr=np.array([1,2,3,4,5])
print(arr[1:4])
print(arr[1:])
print(arr[:4])
print(arr[::2])

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 3 5]


In [12]:
#copy in python list
nums=[1,2,3,4,5]
sub_list=nums[1:3]
print(sub_list)
sub_list[0]=200
print(sub_list)
print(nums)

#view in numpy array
arr=np.array([1,2,3,4,5])
sub_arr=arr[1:3]
print(sub_arr)
sub_arr[0]=200
print(sub_arr)
print(arr)

[2, 3]
[200, 3]
[1, 2, 3, 4, 5]
[2 3]
[200   3]
[  1 200   3   4   5]


In [13]:
#Multi-Dimensional Array
arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)

print(np.sum(arr2D))

sum_of_column=np.sum(arr2D, axis=0)
print(sum_of_column)

sum_of_row=np.sum(arr2D, axis=1)
print(sum_of_row)

print(arr2D[0:2 , 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [14]:
#3D Array
arr3D=np.array([ [ [1,2], [3,4], [5,6] ] , [ [7,8], [9,10], [11,12] ] ])
print(arr3D, arr3D.shape)

#indexing
print(arr3D[0,2,1])
print(arr3D[1,1,1])

#slicing
print(arr3D[:,0,:])      #first row from both layers
print(arr3D[:,:,0])      #first col from both layers

#manipulating data
arr3D[:,0,:]=99
print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
6
10
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


In [15]:
#vectorization 
arr=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])

print(arr**2)
print(arr+10)
print(arr+arr2)

[ 1  4  9 16 25]
[11 12 13 14 15]
[ 7  9 11 13 15]


In [16]:
#Broadcasting
arr=np.array([1,2,3,4,5])
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr.shape)
print(arr2.shape)
print(arr+arr2)

(5,)
(2, 5)
[[ 2  4  6  8 10]
 [ 7  9 11 13 15]]


In [17]:
# Mathematical Functions
#Aggregation Functions

arr = np.array([1, 2, 3, 4, 5])

print(np.sum(arr))     # 15
print(np.prod(arr))    # 120
print(np.min(arr))     # 1
print(np.argmin(arr))  # 0
print(np.max(arr))     # 5
print(np.argmax(arr))  # 4
print(np.mean(arr))    # 3.0
print(np.median(arr))  # 3.0
print(np.std(arr))     # 1.41
print(np.var(arr))     # 2.0

15
120
1
0
5
4
3.0
3.0
1.4142135623730951
2.0


In [18]:
#power function
arr = np.array([1, 2, 3, 4, 5])

print(np.square(arr))    
print(np.sqrt(arr))      
print(np.pow(arr, 3))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [19]:
#log function 
arr = np.array([1, 2, 3, 4, 5])

print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [20]:
#rounding function
print(np.round(2.678))    
print(np.floor(2.678))    
print(np.ceil(2.478))     
print(np.trunc(2.678))

3.0
2.0
3.0
2.0


In [21]:
#Miscellaneous Functions
arr = np.array([1, 2, -5, 3, -8, 4, 2, 5])

print(np.abs(arr))     
print(np.sort(arr))    
print(np.unique(arr)) 

[1 2 5 3 8 4 2 5]
[-8 -5  1  2  2  3  4  5]
[-8 -5  1  2  3  4  5]
